// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {httpmanage} from '../models';
import {utils} from '../models';
import {filesystem} from '../models';
import {context} from '../models';

export function DownloadUrlToPath(arg1:httpmanage.DownloadPayload):Promise<string>;

export function GetCpuInfo():Promise<utils.CpuInfo>;

export function OpenDirByDialog():Promise<filesystem.DirPathResult>;

export function SaveDataToFile(arg1:filesystem.SaveFilePayload):Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;
