// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';
import {context} from '../models';

export function DownloadUrlToPath(arg1:string,arg2:string):Promise<string>;

export function OpenDirByDialog():Promise<filesystem.DirPathResult>;

export function Shutdown(arg1:context.Context):Promise<void>;
