// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadUrlToPath(arg1, arg2) {
  return window['go']['core']['App']['DownloadUrlToPath'](arg1, arg2);
}

export function OpenDirByDialog() {
  return window['go']['core']['App']['OpenDirByDialog']();
}

export function Shutdown(arg1) {
  return window['go']['core']['App']['Shutdown'](arg1);
}
